version: 0.2

env:
  variables:
    SOURCE_ARTIFACTS_PATH="source-artifacts/"
    BUILD_ARTIFACTS_PATH="build-artifacts/"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python menu_script.py
  post_build:
    commands:
      - aws s3 sync $BUILD_ARTIFACTS_PATH s3://www.i-morgen.link/test 




